### PR TITLE
Update Vuetify to v.2.0.1

### PR DESCRIPTION
**Pull request by Ania-chan**
## Description
Updated Vuetify to v.2.0.1 and made necessary changes to the code 

## Issue
https://github.com/VueVixens/website/issues/75

Please let me know if there is anything I should change!

### CODE REVIEW

**Comment by MicheleCynowicz** [comment]
Hello @Ania-chan! The conflicts in this PR are the fault of our `VueVixens/website.git` project having the `.nuxt` directory present in our git history. The `.nuxt` directory should be subject to `.gitignore` - which it is - but the files in our git history are causing problems with PRs like yours.

Earlier today we merged a git deletion of the `.nuxt` directory to the `VueVixens/website.git` master, so if you could pull the latest master from the origin to this branch, the updated PR should have no conflicts and we can approve and merge your changes 🎉

**Comment by jlooper** [comment]
I have merged this branch to Dev. There are many visual issues that need to be fixed, however; you can compare vue-vixens-dev.netlify.com (dev) with vuevixens.org (master). Typeface, centering, removing 'flat' and adding 'text', button spacing...each page needs a careful QA. Thanks!

**Comment by Ania-chan** [comment]
@jlooper Sorry for not noticing this 😿 I'll try to fix the styles as soon as possible!

**Comment by jlooper** [comment]
> @jlooper Sorry for not noticing this 😿 I'll try to fix the styles as soon as possible!

Thank you Ania! I wonder if there might be an issue with node-sass and sass, and also perhaps we don't need the extra material font, is it changing the base font? thanks again!

**Comment by JessicaSachs** [comment]
Just checked this fork out. It looks great to me! Because the changes are substantial, I'm going to fork off of your branch to complete the Nuxt upgrade.

**Comment by Ania-chan** [comment]
@JessicaSachs Sorry so much for the delay with this issue! I still have some CSS issues left to fix :( there seems to be a problem with sass after the update

**Comment by JessicaSachs** [comment]
! omg I was comparing the wrong branch. Doy. Thank you 🤦‍♀

**Comment by JessicaSachs** [comment]
Do you mind if I look through your branch?

**Comment by Ania-chan** [comment]
@JessicaSachs  Sure!

**Comment by Ania-chan** [comment]
@MicheleCynowicz @jlooper I finally fixed the styles! I'm really sorry it took so long...
I have a feeling that new version on Vuetify might have changed something in the styles for `v-card__title` because they were broken on `Sponsors` and `Team` pages. I fixed it for each page individually but I feel there might be a better way to solve it because it's a bit repetitive. Unfortunately I couldn't find where the new styles are coming from. 

Please let me know if there is anything I should fix!

**Pull request closed without merging**
